---
- name: install & configure docker & docker-compose on Ubuntu
  hosts: all
  become: true
  vars:
    docker_user: root
  roles:
    - docker
  tags: deploy-prod

- name: deploy production server
  hosts: production
  become: true
  vars:
    github_branch: deploy-ansible
  roles:
    - deploy
  tags: deploy-prod

- name: install monitoring stack
  hosts: monitor
  become: yes
  roles:
    - prometheus
    - grafana
  tags: monitoring
  
- name: install node-exporter
  hosts: all
  become: yes
  roles:
    - node-exporter
  tags: monitoring