---
- name: Copy Prometheus Config File
  copy: 
    src: prometheus.yml
    dest: ~/prometheus/

- name: Copy Alert Role File
  copy: 
    src: alert.rules
    dest: ~/prometheus/

- name: Create prometheus containers
  docker_container:
    name: "{{container_name}}"
    image: "{{ docker_images }}"
    command: "{{ container_command}}"
    volumes: "{{ container_volumes}}"
    # depends_on: "{{ container_depends}}"